COMMA_SPACE = ", "

PAR_CLOSING = ")"
PAR_OPENING = "("

DOUBLE_QUOTE = "\""
QUOTE = "'"
QUOTE_PAR_CLOSING = QUOTE + PAR_CLOSING
QUOTE_COMMA_SPACE = QUOTE + COMMA_SPACE
DOUBLE_QUOTE_COMMA_SPACE = DOUBLE_QUOTE + COMMA_SPACE
